import test from 'node:test';
import assert from 'node:assert/strict';
import {analyzeText,syncDetectedParticipants,applyReview,syncJourneys} from '../dist/document-model.mjs';
import {participantProgress,renderDashboard} from '../dist/trip-dashboard.mjs';
import {createDocumentFeatures} from '../dist/document-ui.mjs';
function fixture(){const t={people:[],vehicles:[],files:[{path:'a.pdf'}],readings:{'a.pdf':{...analyzeText({people:[],text:'Passenger: Anna Soler\nFrom: BCN\nTo: MXP\nDeparture: 11/10/2026 11:30\nArrival: 11/10/2026 13:15\nFlight: VY6342'}),status:'ready',fingerprint:'a'}}};syncDetectedParticipants(t);return t;}
test('cached readings attach journeys to participant and reload stays idempotent',()=>{const t=fixture();assert.equal(t.people[0].journeys[0].destination,'MXP');assert.equal(t.people[0].journeys[0].documentPath,'a.pdf');assert.equal(syncDetectedParticipants(t).updated,0);});
test('participant UI shows detected route and arrival without manual confirmation',()=>{const t=fixture(),ui=createDocumentFeatures({esc:String});assert.match(ui.journeySummary(t,t.people[0]),/BCN → MXP/);assert.match(ui.arrivalSummary(t,t.people[0]),/13:15/);t.people[0].arrival='Manual';assert.equal(ui.arrivalSummary(t,t.people[0]),'Manual');});
test('review updates saved participant journeys and ignored document removes them',()=>{let t=fixture();t=applyReview(t,'a.pdf',t.readings['a.pdf'].proposals.map(p=>({...p,enabled:true})));assert.equal(t.people[0].journeys[0].pending,false);t.readings['a.pdf'].status='ignored';t.readings['a.pdf'].confirmed=[];syncJourneys(t);assert.deepEqual(t.people[0].journeys,[]);});
test('detected booking never counts as completed ticket or check-in',()=>{const t=fixture(),r=participantProgress(t,t.people[0]);assert.equal(r.complete,false);assert.deepEqual(r.pending.map(c=>c.key),['journeys','ticket','checkin','pickup']);});
test('reviewed route and completed logistics mark participant ready',()=>{let t=fixture();t=applyReview(t,'a.pdf',t.readings['a.pdf'].proposals.map(p=>({...p,enabled:true})));Object.assign(t.people[0],{ticket:'Comprat',checkin:'Fet',pickup:'Driver at terminal'});assert.equal(participantProgress(t,t.people[0]).complete,true);assert.match(renderDashboard(t,'pending',String),/Cap participant amb aquest pendent/);});
test('stale or incomplete transport still appears as pending',()=>{const t=fixture();Object.assign(t.people[0],{ticket:'No cal',checkin:'No cal',vehicle:'v'});t.vehicles=[{id:'v',name:'Van',driver:'Pau'}];assert.equal(participantProgress(t,t.people[0]).pending[0].key,'pickup');});
