import test from 'node:test';
import assert from 'node:assert/strict';
import {rosterRows,resetWithRoster,cachedRoster} from '../dist/roster.mjs';
import {analyzeText,syncDetectedParticipants,applyReview} from '../dist/document-model.mjs';
const rows=[['Títol'],['Nº','Nom i cognoms','Rol'],['1','Anna Soler','Atleta'],['2','Pau Serra','Tècnic'],['','','']];
test('Excel reset uses only roster names and clears previous links',()=>{const source={id:'t',name:'Trip',people:[{id:'old',name:'Other'}],vehicles:[],files:[{path:'x'}],folder:{name:'old'},readings:{x:{}}};const t=resetWithRoster(source,rosterRows([rows]),'team.xlsx');assert.equal(t.people.length,2);assert.deepEqual(t.files,[]);assert.deepEqual(t.readings,{});assert.equal(t.folder,null);assert.equal(t.people[0].ticket,'Pendent');assert.equal(source.people[0].name,'Other');});
test('documents only match roster and unknown passenger stays unresolved',()=>{const t=resetWithRoster({vehicles:[]},rosterRows([rows]),'team.xlsx');t.readings.a={...analyzeText({people:t.people,text:'Passengers:\nAnna Soler\nJulia Puig\nFrom: BCN\nTo: MXP'}),status:'ready',fingerprint:'a'};syncDetectedParticipants(t);assert.equal(t.people.length,2);assert.equal(t.readings.a.proposals.find(p=>p.name==='Julia Puig').unmatched,true);assert.ok(t.people[0].journeys.length);assert.throws(()=>applyReview(t,'a',[{enabled:true,name:'Julia Puig',segments:[]}]),/Excel/);});
test('cached Excel can prepare reset without reselecting it',()=>{const r=cachedRoster({readings:{a:{name:'team.xlsx',text:rows.map(r=>r.join(' | ')).join('\n')}}});assert.equal(r.rows.length,2);assert.equal(r.source,'team.xlsx');});
test('roster document itself cannot assign flights or add participants',()=>{const t=resetWithRoster({vehicles:[]},rosterRows([rows]),'team.xlsx');t.readings.a={name:'team.xlsx',status:'ready',fingerprint:'a',text:'Passenger: Other Name',proposals:[]};syncDetectedParticipants(t);assert.equal(t.people.length,2);assert.deepEqual(t.people[0].journeys,[]);});
