import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFile} from 'node:fs/promises';
import worker from '../dist/server/index.js';
import {personalView,validateSnapshot,sharedSnapshot} from '../dist/shared-trip.mjs';
import {pickupGroups,dateParts} from '../dist/pickups.mjs';
function database(){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE shared_trips(id TEXT PRIMARY KEY,payload TEXT NOT NULL,revision INTEGER NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE participant_feedback(trip_id TEXT,person_id TEXT,seen_revision INTEGER,checkin TEXT,updated_at TEXT,PRIMARY KEY(trip_id,person_id));');return {prepare(sql){let values=[];const query={bind(...v){values=v;return query},async first(){return db.prepare(sql).get(...values)||null},async all(){return {results:db.prepare(sql).all(...values)}},async run(){return db.prepare(sql).run(...values)}};return query;}};}
const snapshot=()=>({id:'trip',name:'Camp',people:[{id:'anna',name:'Anna',email:'anna@example.org',journeys:[],bookings:[],transports:[],notes:'Anna only'},{id:'pau',name:'Pau',email:'pau@example.org',notes:'Private other person'}]});
const req=(path,email,method='GET',body,origin='https://test.site')=>new Request('https://test.site'+path,{method,headers:{...(email?{'oai-authenticated-user-id':'u-'+email,'oai-authenticated-user-email':email}:{}),origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
const env=()=>({DB:database(),ADMIN_EMAIL:'owner@example.org'});
async function publish(e,trip=snapshot(),expectedRevision=0){return worker.fetch(req('/api/admin/trips/trip','owner@example.org','PUT',{trip,expectedRevision}),e);}
test('server gates admin APIs and redirects unauthenticated browser sign-in',async()=>{const e=env();assert.equal((await worker.fetch(req('/api/admin/trips','anna@example.org'),e)).status,403);assert.equal((await worker.fetch(req('/api/my-trips',null),e)).status,401);assert.match((await worker.fetch(req('/me',null),e)).headers.get('location'),/signin-with-chatgpt/);});
test('server returns only the authenticated athlete, never the roster or other bookings',async()=>{const e=env();assert.equal((await publish(e)).status,200);const response=await worker.fetch(req('/api/my-trips','anna@example.org'),e),data=await response.json();assert.equal(data.trips[0].person.id,'anna');assert.equal(JSON.stringify(data).includes('Private other person'),false);assert.deepEqual((await (await worker.fetch(req('/api/my-trips','stranger@example.org'),e)).json()).trips,[]);});
test('athlete cannot publish or confirm someone else’s trip; check-in changes are scoped',async()=>{const e=env();await publish(e);assert.equal((await worker.fetch(req('/api/admin/trips/trip','anna@example.org','PUT',{trip:snapshot(),expectedRevision:1}),e)).status,403);assert.equal((await worker.fetch(req('/api/my-trips/trip/feedback','stranger@example.org','POST',{action:'seen',revision:1}),e)).status,403);assert.equal((await worker.fetch(req('/api/my-trips/trip/feedback','anna@example.org','POST',{action:'checkin',checkin:'Fet',revision:1,personId:'pau'}),e)).status,200);const info=await (await worker.fetch(req('/api/admin/trips/trip','owner@example.org'),e)).json();assert.equal(info.feedback[0].person_id,'anna');});
test('concurrent snapshots and stale acknowledgements are rejected',async()=>{const e=env();await publish(e);assert.equal((await publish(e)).status,409);await publish(e,snapshot(),1);assert.equal((await worker.fetch(req('/api/my-trips/trip/feedback','anna@example.org','POST',{action:'seen',revision:1}),e)).status,409);});
test('cross-origin writes are rejected and email removal revokes access',async()=>{const e=env();await publish(e);assert.equal((await worker.fetch(req('/api/admin/trips/trip','owner@example.org','PUT',{trip:snapshot(),expectedRevision:1},'https://evil.test'),e)).status,403);const t=snapshot();t.people[0].email='';await publish(e,t,1);assert.deepEqual((await (await worker.fetch(req('/api/my-trips','anna@example.org'),e)).json()).trips,[]);});
test('snapshot does not upload original PDF text or other document bytes',()=>{const t={id:'x',name:'x',people:[{id:'p',name:'Person',email:'test@example.org'}],vehicles:[],files:[],readings:{x:{text:'secret raw PDF',proposals:[]}}};assert.equal(JSON.stringify(sharedSnapshot(t)).includes('secret raw PDF'),false);const v=snapshot();v.people[1].email=v.people[0].email;assert.throws(()=>validateSnapshot(v),/diferent/);});
test('pickup groups omit connection airport and retain return destination',()=>{const t={start:'2026-10-11',people:[{id:'p'}],vehicles:[],files:[{path:'a'}],readings:{a:{status:'ready',fingerprint:'x',proposals:[{personId:'p',segments:[{origin:'BIO',destination:'MXP',departure:'11/10/2026 10:00',arrival:'11/10/2026 11:55'},{origin:'MXP',destination:'BCN',departure:'26 octubre 2026 17:20',arrival:'26 octubre 2026 19:00'},{origin:'BCN',destination:'BIO',departure:'26 octubre 2026 21:35',arrival:'26 octubre 2026 22:50'}]}]}}};const g=pickupGroups(t);assert.equal(g.length,2);assert.equal(g[0].airport,'MXP');assert.equal(g[1].airport,'BIO');assert.equal(g[1].direction,'Tornada');assert.equal(dateParts('dom. 11 oct. 2026 12:45').date,'2026-10-11');});
